cabledb/src/main/java/org/openepics/cable/ui/LoginController.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 *
 * This file is part of Cable Database.
 * Cable Database is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 2 of the License, or any newer version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package org.openepics.cable.ui;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import org.openepics.cable.services.CableService;
import org.openepics.cable.services.SessionService;

import org.openepics.cable.util.UiUtility;
import org.openepics.cable.util.fbs.FbsService;
import se.esss.ics.rbac.loginmodules.service.Message;

/**
 * A UI controller bean for the login / logout button and form.
 *
 * @author <a href="mailto:sunil.sah@cosylab.com">Sunil Sah</a>
 */
@ManagedBean
@ViewScoped
public class LoginController implements Serializable {

    private static final long serialVersionUID = 5984791196886929176L;

    private static final Logger LOGGER = Logger.getLogger(LoginController.class.getName());

    private static final String UNEXPECTED_ERROR = "Unexpected error";

    @Inject
    private SessionService sessionService;
    @Inject
    private CableService cableService;
    @Inject
    private FbsService fbsService;

    private String inputUsername;
    private String inputPassword;

    private boolean loginRequested;

    private void clearPassword() {
        inputPassword = null;
    }

    /** Initializes the bean for initial view display. */
    @PostConstruct
    public void init() {
        loginRequested = !sessionService.isLoggedIn();
    }

    /** Requests login. */
    public void requestLogin() {
        LOGGER.fine("Invoked request login.");
        loginRequested = true;
    }

    /** Performs login. */
    public void login() {
        LOGGER.fine("Invoked login.");
        try {
            final Message result = sessionService.login(inputUsername, inputPassword);
            if (result.isSuccessful()) {
                loginRequested = false;
                UiUtility.showMessage(
                        FacesMessage.SEVERITY_INFO, "You are logged in", "Welcome " + inputUsername + "!");
            } else {
                UiUtility.showMessage(FacesMessage.SEVERITY_ERROR, "Login failed!", "Please try again.");
            }
        } catch (Exception e) {
            UiUtility.showMessage(FacesMessage.SEVERITY_ERROR, "Login failed!", "Please try again.");
            LOGGER.log(Level.INFO, "Login failed for " + inputUsername);
            LOGGER.log(Level.FINE, "Login failed for " + inputUsername, e);
        } finally {
            clearPassword();
        }
    }

    /** Performs logout. */
    public void logout() {
        LOGGER.fine("Invoked logout.");
        try {
            final Message result = sessionService.logout();
            UiUtility.showMessage(FacesMessage.SEVERITY_INFO, "Logout", "You have been logged out.");
        } catch (Exception e) {
            UiUtility.showMessage(FacesMessage.SEVERITY_ERROR, "Logout", "Logout has failed.");
            LOGGER.log(Level.FINE, "Strangely, logout has failed.", e);
        } finally {
            clearPassword();
        }
        loginRequested = true;
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect(
                    FacesContext.getCurrentInstance().getExternalContext().getApplicationContextPath() +
                            FacesContext.getCurrentInstance().getViewRoot().getViewId());
        } catch (IOException e) {
            LOGGER.log(Level.SEVERE, UNEXPECTED_ERROR, e);
        }
        return;
    }

    /** Cancels login in progress. */
    public void cancel() {
        LOGGER.fine("Invoked cancel.");
        clearPassword();
        loginRequested = false;
    }

    /** @return the inputUsername */
    public String getInputUsername() {
        return inputUsername;
    }

    /**
     * @param inputUsername
     *            the inputUsername to set
     */
    public void setInputUsername(String inputUsername) {
        this.inputUsername = inputUsername;
    }

    /** @return the inputPassword */
    public String getInputPassword() {
        return inputPassword;
    }

    /**
     * @param inputPassword
     *            the inputPassword to set
     */
    public void setInputPassword(String inputPassword) {
        this.inputPassword = inputPassword;
    }

    /** @return the true if the login is currently requested, else false */
    public boolean isLoginRequested() {
        return loginRequested;
    }

    /** @return the true, if the login will be redirected to cable page */
    public boolean isCablesPage() {
        return "/cables.xhtml".equals(FacesContext.getCurrentInstance().getViewRoot().getViewId());
    }
}

cabledb/src/main/webapp/WEB-INF/cableTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html">

<h:head>
  <f:facet name="first">
    <meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
  </f:facet>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <link href="resources/css/default.css" rel="stylesheet"
    type="text/css" />
  <link href="resources/css/cssLayout.css" rel="stylesheet"
    type="text/css" />
  <title>#{msgs.title}</title>
  <h:outputScript library="js" name="cabledb-common.js" />
  <ui:insert name="head_content" />
</h:head>

<h:body>

  <p:dialog modal="true" widgetVar="statusDialog" showHeader="false"
    draggable="false" closable="false" resizable="false">
    <p:graphicImage value="/resources/images/ajax-loader.gif" />
  </p:dialog>

  <p:outputPanel id="full" layout="block">

  <div class="app_header">
      <div class="logo">
            <h:outputText value="#{msgs.title}" styleClass="gui-title"/>
      </div>
      <div>
            <ui:include src="/WEB-INF/includes/tabmenu.xhtml" />
      </div>
      <div>
            <ui:include src="/WEB-INF/includes/dropmenu.xhtml" />
      </div>
  </div>

    <div style="padding: 15px 15px 0px 15px">
      <p:growl id="cableDBGrowl" showDetail="true" />
      <ui:insert name="content">Content</ui:insert>
    </div>
  </p:outputPanel>

  <h:form id="loginForm">
    <p:dialog id="loginDialog" widgetVar="loginDialog" modal="true"
      visible="#{loginController.loginRequested}" closable="false">

      <f:facet name="header">
        <h:outputText value="Sign In" />
      </f:facet>
      <p:panelGrid id="grid" columns="2" styleClass="borderless">
        <h:outputLabel for="username" value="Username" />
        <h:panelGroup>
          <p:inputText id="username"
            value="#{loginController.inputUsername}" label="Username" />
          <p:watermark for="username" value="Enter username" />
          <p:message for="username" />
        </h:panelGroup>
        <h:outputLabel for="passwd" value="Password" />
        <h:panelGroup>
          <p:password id="passwd"
            value="#{loginController.inputPassword}" label="Password" />
          <p:watermark for="passwd" value="Enter password" />
          <p:message for="passwd" />
        </h:panelGroup>
      </p:panelGrid>
      <p:separator />

      <p:commandButton value="Sign In" update=":full :loginForm"
        action="#{loginController.login()}" style="float: left"
        onstart="start()" oncomplete="stop(); if (#{userManager.loggedIn}){remoteCommandLoad();};"
        rendered="#{loginController.cablesPage}" />

      <p:commandButton value="Sign In" update=":full :loginForm"
        action="#{loginController.login()}" style="float: left"
        onstart="start()" oncomplete="stop()"
        rendered="#{!loginController.cablesPage}" />

    </p:dialog>
  </h:form>

  <p:dialog modal="true" id="popupDialog" header="Warning" widgetVar="popupDialog"
            visible="#{applicationStateManager.namesServiceWarning}" closable="true" resizable="false">
    <div class="ui-fluid">
      <p:outputLabel value="The connection to the Naming Service could not be
      established."/>
    </div>
    <p:spacer width="32"/>
    <p:panel style="text-align: right; padding: 0; border: 0;" styleClass="dialogButtonPanel">
      <p:commandButton value="Close" title="Close dialog."
                       style="float:right" onclick="PF('popupDialog').hide();"
                       icon="ui-icon-close"/>
    </p:panel>
  </p:dialog>

  <script type="text/javascript">
            jQuery(window).resize(function() {
                adjustFooterPosition();
            });

            jQuery(document).ready(function() {
                adjustFooterPosition();
            });
        </script>

  <ui:include src="/resources/dialogs/error-dialog.xhtml" />
</h:body>

</html>

cabledb/src/main/webapp/WEB-INF/historyDataTable.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:pe="http://primefaces.org/ui/extensions">
  <div style="width: calc(100% - 1em)">

    <p:remoteCommand name="updatePageSize" action="#{historyRequestManager.onPaginatePageSize}" />

    <p:dataTable id="historyTable" var="history"
      value="#{controller.lazyModel}" rowKey="#{history.id}"
      widgetVar="historyTable" class="dialogListTable"
      emptyMessage="No records found."
      scrollable="true"
      scrollWidth="100%"
      scrollHeight="#{tableHeight}"
      rows="#{controller.rows}"
      lazy="true"
      paginator="true"
      paginatorAlwaysVisible="true"
      paginatorPosition = "bottom"
      paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} Rows/page: {RowsPerPageDropdown}"
      currentPageReportTemplate="Total: {totalRecords} records"
      rowsPerPageTemplate="10,20,30,40,50"
      resizableColumns="true"
      resizeMode="expand">

      <p:ajax event="page" process="@this"
        listener="#{controller.onPaginate}"
        update="tableMenuActions"
        oncomplete="updatePageSize()" />
      <p:ajax event="filter" update="#{updateOnFilter}" />
      <p:ajax event="sort"
            onstart="start();"
            oncomplete="stop();" />

      <f:facet name="header">
        <p:commandButton id="toggler" type="button" value="Columns" style="float:left" title="Select columns"/>
        <p:columnToggler datasource="historyTable" trigger="toggler">
          <p:ajax event="toggle" listener="#{historyRequestManager.onToggle}" />
        </p:columnToggler>

        <p:menuButton id="tableMenuActions" value="Actions" style="float: right; text-align: left;">
          <p:menuitem
            id="exportLogButton" value="Export" onstart="start()"
            title="Export log" icon="ui-icon-disk" update=":dialogs"
            oncomplete="PF('exportDialog').show(); stop();"
            onclick="disableButtons('logTableForm','buttons');"  class = "button"
            disabled="#{historyRequestManager.historyEmpty}" />

          <p:separator />
          <p:menuitem
            value="Close" title="Close history dialog"
            onclick="PF('#{widgetName}').hide();"
            action="#{controller.clearHistory()}" icon="ui-icon-close" />
         </p:menuButton>
      </f:facet>

      <p:column id="timestampColumn" sortBy="#{history.timestamp}"
        styleClass="data_table_header"
        style="width:15%; min-width:100px"
        filterStyle="width:100%;"
        filterBy="#{history.timestamp}"
        filterMatchMode="contains"
        visible="#{historyRequestManager.isColumnVisible(0)}">
        <f:facet name="header">
          <h:outputText value="Timestamp"
            title="History entry timestamp" />
        </f:facet>
        <h:outputText value="#{history.timestamp}"/>
      </p:column>

      <p:column id="userColumn" sortBy="#{history.userId}"
        styleClass="data_table_header"
        style="width:10%; min-width:100px"
        filterStyle="width:100%;"
        filterBy="#{history.userId}"
        filterMatchMode="contains"
        visible="#{historyRequestManager.isColumnVisible(1)}">
        <f:facet name="header">
          <h:outputText value="User" title="User" />
        </f:facet>
        <h:outputText value="#{history.user}"/>
      </p:column>

      <p:column id="entityType" sortBy="#{history.entityType}"
        styleClass="data_table_header"
        style="width:10%; min-width:60px"
        filterStyle="width:100%;"
        filterBy="#{history.entityType}" filterMatchMode="exact"
        filterOptions="#{historyRequestManager.entityTypeValues}"
        visible="#{historyRequestManager.isColumnVisible(2)}"
        rendered="#{showType}">
        <f:facet name="header">
          <h:outputText value="Entity Type" title="Entity Type" />
        </f:facet>
        <h:outputText value="#{history.entityType}"/>
      </p:column>

      <p:column id="operationColumn" sortBy="#{history.operation}"
        styleClass="data_table_header"
        style="width:10%; min-width:60px"
        filterStyle="width:100%;"
        filterBy="#{history.operation}" filterMatchMode="exact"
        filterOptions="#{historyRequestManager.operationValues}"
        visible="#{historyRequestManager.isColumnVisible(3)}">
        <f:facet name="header">
          <h:outputText value="Operation" title="Operation" />
        </f:facet>
        <h:outputText value="#{history.operation}"/>
      </p:column>

      <p:column id="entityNameColumn" sortBy="#{history.entityName}"
        styleClass="data_table_header"
        style="width:20%; min-width:100px"
        filterStyle="width:100%;"
        filterBy="#{history.entityName}"
        filterMatchMode="contains"
        visible="#{historyRequestManager.isColumnVisible(4)}">
        <f:facet name="header">
          <h:outputText value="Entity Name" title="Entity name" />
        </f:facet>
        <h:outputText value="#{history.entityName}"/>
      </p:column>

      <p:column id="entityIdColumn" sortBy="#{history.entityId}"
        styleClass="data_table_header"
        style="width:10%; min-width:60px"
        filterStyle="width:100%;"
        filterBy="#{history.entityId}"
        filterMatchMode="contains"
        visible="#{historyRequestManager.isColumnVisible(5)}">
        <f:facet name="header">
          <h:outputText value="Entity ID" title="Entity ID" />
        </f:facet>
        <h:outputText value="#{history.entityId}"/>
      </p:column>

      <p:column id="entryColumn" sortBy="#{history.entry}"
        styleClass="data_table_header"
        style="width:25%; min-width:150"
        filterStyle="width:100%;"
        filterBy="#{history.entry}"
        filterMatchMode="contains"
        visible="#{historyRequestManager.isColumnVisible(6)}">
        <f:facet name="header">
          <h:outputText value="Change" title="Change description" />
        </f:facet>
        <p:commandLink update=":#{popupName}Form"
          oncomplete="PF('#{popupName}').show('#{component.clientId}');"
          styleClass="ellipsis">
          <f:setPropertyActionListener value="Change"
            target="#{historyRequestManager.longTextOverlayHeader}" />
          <f:setPropertyActionListener value="#{history.entry}"
            target="#{historyRequestManager.longTextOverlayContent}" />
          <h:outputText value="#{history.entry}" title="Open History dialog"/>
        </p:commandLink>
      </p:column>

    </p:dataTable>

    <pe:tooltip value="Jump to page (number can be typed on keyboard)" for="@(.ui-paginator-jtp-select)"
                atPosition="top center" myPosition="bottom center" showDelay="300"
                header="Information"/>

    <pe:tooltip value="Rows/page" for="@(.ui-paginator-rpp-options)"
                atPosition="top center" myPosition="bottom center" showDelay="300"
                header="Information" />
  </div>
  <script>
    function fixFiltersTabindex() {
      document.querySelector('[id$="historyTable"]').querySelectorAll('[id$="filter"]').forEach(function(item) {item.tabIndex = 0;});
    }

    fixFiltersTabindex();
  </script>
</ui:composition>